### ISSUE TITLE
what's the difference between ol7-xx and ol8 xx

### ISSUE THREAD

**Issue by tellmewhattodo** [graalvm/container#57]
ol8-java11-22.1.0-b1
ol8-java11-22.1.0
ol7-java11-22.1.0

what's the difference

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out to us. The naming convention for our images is the following:
<OS>-<java_version>-<graalvm-version>-<build>
`ol8-java11-22.1.0-b1` is the build `b1` of GraalVM version `22.1.0` for java`11` on Oracle Linux 8 (`ol8`)
Since we only have 1 build released, `ol8-java11-22.1.0` refers to the same image as `ol8-java11-22.1.0-b1`, In case we add a new build for the same version, using the tag `ol8-java11-22.1.0-b1` will always pull the build `b1` even if newer builds are available, while `ol8-java11-22.1.0` will pull the latest available build.
Finally, `ol7-java11-22.1.0` refers to the same version of GraalVM but on top of Oracle Linux 7 (ol7).
Hope I clarified things for you.
