### ISSUE TITLE
Where is the docker file for ghcr.io/graalvm/graalvm-ce:latest

### ISSUE THREAD

**Issue by Semptic** [graalvm/container#7]
We where used to use `yum` to install additional tools into the container. Before we where using the version hosted on docker-hub. Now we switched to use [ghcr.io/graalvm/graalvm-ce:latest](https://github.com/orgs/graalvm/packages/container/package/graalvm-ce) (since the docker-hub one is gone). 

Running
```
$ docker run -ti ghcr.io/graalvm/graalvm-ce:latest uname -a
Linux 6761594d38d0 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Tells me that it's now using Ubuntu. Where can I find the Dockerfile for ghcr.io/graalvm/graalvm-ce:latest?

**Comment by abdelhaira** [comment]
The uname command will tell you the kernel that's running, which is the host OS kernel, since containers, unlike VM's, share the same kernel(i presume in this case you're running docker in ubuntu machine or on windows/wsl2 backend which is ubuntu).
If you want to see container os info use: cat /etc/os-release  
```
bash-4.4# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:3:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.3
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.3
```

The reason why you can't find yum, is because graalvm-ce use oraclelinux:8-slim as base image which doesn't contain neither yum or dnf, but it has microdnf which can you can use.  

if you want to create your own image which includes yum use oraclelinux:8 as the base image, the Dockerfile is in this repo,for the latest tag is Dockerfile.ol8-java11, just bump the version accordingly and build it.

**Comment by ezzarghili** [comment]
@Semptic the `Dockerfile` files used for building the images are those in this repo, you would only need to pass the new version as argument to build the image (no change to code), `--build-arg GRAALVM_VERSION=21.0.0` for instance.
The one used for the latest tag is https://github.com/graalvm/container/blob/master/community/Dockerfile.ol8-java11

**Comment by Semptic** [comment]
Thanks a lot.
