### ISSUE TITLE
native image muslib images are missing arm64 image varian

### ISSUE THREAD

**Issue by cmdjulian** [graalvm/container#70]
I'm wondering if this is a conscious decision, as all native image images using muslib only seem to have an amd64 variant, no arm64 variant though. I did not find any documentation regarding this.  
I'm build on arm64 with `ghcr.io/graalvm/native-image:muslib-ol9-java17-22.3.0`. As the image is not natively available as arm64, my mac just falls back to the amd64 variant and uses this one in my multi-arch build targeting arm64 and amd64. This results in no error while building. When I now try to start my build image, it fails with an exec format error as the binary is amd64. This is rather unfortunate, as I took quite a while to figure that out...

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, we'll take a look into it shortly.

**Comment by everflux** [comment]
As the musl based build is required for -static linking it would be really appreciated if musl based images could be provided.

**Comment by oubidar-Abderrahim** [comment]
We cannot provide an ARM64 muslib image yet simply because GraalVM supports muslib only on AMD64 as mentioned [here](https://www.graalvm.org/22.0/reference-manual/native-image/StaticImages/#prerequisites).

I suggest creating a feature request under the appropriate repository: https://github.com/oracle/graal/issues to support muslib on arm64; Once a build with that support is available, we'll be happy to provide docker images for it.

**Comment by axelfontaine** [comment]
Needing this as well, I went ahead and created https://github.com/oracle/graal/issues/5872
