### ISSUE TITLE
`GLIBC_2.32` not found in `:17-ol9`

### ISSUE THREAD

**Issue by xlight05** [graalvm/container#79]
Hi all,
I'm using a multistage build where I execute the native-image command with mostly static flag using `ghcr.io/graalvm/native-image-community:17-ol9` container. Then I'll copy the executable generated, to distroless container(with glibc). This approach worked just fine without any issues in ol7 and ol8 but when I tried to use ol9 image. I'm getting the following error.
```./hello: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./hello)```

This issue is reproducible in both `native-imag` and `native-image-commiunity` containers. This issue is not reproducible and works just fine when we use ol7, ol8.

I thought mostly static flag does not pack libc in the executable?

### Steps to reproduce
```
git clone https://github.com/xlight05/graal_ol9_issue
docker build -t test_svc .
docker run  -p 9090:9090 test_svc
```

Change the base image from `ghcr.io/graalvm/native-image-community:17-ol9` to `ghcr.io/graalvm/native-image-community:17-ol8` and it should work normally. 
```
curl http://localhost:9090/helloWorld/sayHello
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly

**Comment by mlouriz** [comment]
Hi @xlight05 thank you for reporting this, It seems that the ol9 image has a newer version of Glibc (2.34). Please try to upgrade the Glibc package to the 2.34 version in [gcr.io/distroless/base](http://gcr.io/distroless/base). Otherwise use the muslib image we provide to build a static native-image you can use this image `docker pull ghcr.io/graalvm/native-image-community:17-muslib-ol9`.
