### ISSUE TITLE
Image `ghcr.io/graalvm/native-image-community:21-muslib` cannot build native image inside docker

### ISSUE THREAD

**Issue by rost5000** [graalvm/container#87]
## System requirements
* Windows/Linux
* Docker
## Step to reproduce
1. Run the following command:
```bash
git clone https://github.com/rost5000/graalvm-docker-build-bug.git && cd ./graalvm-docker-build-bug && docker build .
```
2. You can see the error:
```text
#0 3.513 Failed generating 'application' after 2.0s.
#0 3.513
#0 3.513 The build process encountered an unexpected error:
#0 3.513
#0 3.513 > com.oracle.svm.core.util.VMError$HostedError: Unable to run '/tmp/SVM-2564794841615393060/BuiltinDirectives' to compute offsets in C data structures. Is it possible that your antivirus software interferes and puts the resulting file into quarantine?
#0 3.513
#0 3.513 Please inspect the generated error report at:
#0 3.513 /home/app/ms/svm_err_b_20231103T112642.867_pid49.md
#0 3.515
#0 3.515 If you are unable to resolve this problem, please file an issue with the error report at:
#0 3.515 https://graalvm.org/support
------
Dockerfile:15
--------------------
  14 |
  15 | >>> RUN native-image -cp /home/app/ms/build/libs/graalvm-1.0-SNAPSHOT.jar \
  16 | >>>     -H:Class=org.example.Main \
  17 | >>>     -H:Name=application \
  18 | >>>     --no-fallback
  19 |
--------------------
ERROR: failed to solve: process "/bin/sh -c native-image -cp /home/app/ms/build/libs/graalvm-1.0-SNAPSHOT.jar     -H:Class=org.example.Main     -H:Name=application     --no-fallback" did not complete successfully: exit code: 1
```
3. It was worked in ` ghcr.io/graalvm/native-image:ol7-java17-22.3.2` image
4. If I prepare my own image with installation graalvm and c libs, everything is works.

**Comment by mlouriz** [comment]
Hi @rost5000, It seems that you are using the muslib image (it's a native image container image that has muslib in the tags) as the base of your Dockerfile. FYI, muslib image is used to build a static native executable for more information please refer to this [documentation](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/). To fix your issue all you need is to use **ghcr.io/graalvm/native-image-community:21** instead of **ghcr.io/graalvm/native-image-community:21-muslib**. Please feel free to open new ticket if you are facing any issue.
