### ISSUE TITLE
container tagged as 22 but java version still 17

### ISSUE THREAD

**Issue by sombriks** [graalvm/container#90]
I am trying to build with java 21 and generate a native image for that jvm version. 

however native image fails because it still using jvm 17

![image](https://github.com/graalvm/container/assets/556695/2e767a94-a8c7-4beb-9e75-76b064dc024f)

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this. 

The tag `22` refers to GraalVM version `22.3`, not the JDK version. This was how we used to tag GraalVM images before, by referring to the GraalVM version. see [native-image](https://github.com/graalvm/container/pkgs/container/native-image) 

We discontinued the releases of GraalVM following this approach since July 2023 (the last version available is 22.3.3)

For the new native-image docker images, please use `FROM ghcr.io/graalvm/native-image-community:21` and check [native-image-community](https://github.com/graalvm/container/pkgs/container/native-image-community) for more tags.

Please note that JDK 22 is not released yet therefore there are no available images for that version at the moment.

**Comment by sombriks** [comment]
thanks a lot for the clarification, i'll pay attention on that.

a note on the README woul de helpful, since it still mention other images and does not make clear that native-image is the right one.
